### ISSUE TITLE
Prometheus time series are created for unused actors.

### ISSUE THREAD

**Issue by machine424** [wiremind/remoulade#276]
Hello,

I think we initialize Prometheus time series for all actors even those that are never run by a worker. A worker may only run 1 actor and expose metrics for the XX others, their values will be 0 (well compressed by Prometheus) but the labels still occupy/use resources especially when autoscaling  is enabled on the workers.

It will be great if we could only consider actors that the worker will run.

**Comment by antoinerabany** [comment]
https://github.com/wiremind/remoulade/pull/278
