### ISSUE TITLE
Refactor how options work

### ISSUE THREAD

**Issue by cp2587** [wiremind/remoulade#64]
We should implement the same pattern as celery has: 3 levels of options, with this priority (top being having less priority):

- broker / remoulade default options (ones passed when instanciating broker and middlewares)
- remoulade.actor decorator options
- options passed when calling the actor with actor.send()

**Comment by etiennecrb** [comment]
I guess this is already the case except the global options are hard to set because some middlewares are added to broker by default, without any hook to customize them.
