### ISSUE TITLE
Implement a Message.prior_messages

### ISSUE THREAD

**Issue by cp2587** [wiremind/remoulade#68]
Implement a method Message.prior_messages that returns a list of messages that are schedule to be ran before the message the method is called with. This will allow us to track when will the message will start to be processed. This list can change over time as priority messages can enter the queue at any given time. This API will then be useful both in CLI and in the futur web app to have statistics on scheduled runtime and so on.

**Comment by antoinerabany** [comment]
There is nothing like that in RabbitMQ API, only the number on message in a queue and this is more for monitoring than anything. We could do something with redis, store something when the message is enqueued and processed.
I think this need to be thought more broadly as part of a status feature which would give message status : 'enqued', 'processing', maybe a progress part and 'done'.
The progress part need to introduce something like a bind self of celery.

**Comment by cp2587** [comment]
This has also to take into account priority. 
Not sure how remoulade pull the actor it has to run but when it do, it should maintain a map with actors that remain to process per priority. We can talk about it when you have time
