### ISSUE TITLE
Results don't use expected encoder if changed after backend is created

### ISSUE THREAD

**Issue by etiennecrb** [wiremind/remoulade#9]
# Issues

Results backend sets its encoder using the global one at the moment it is created. If the encoder was changed afterwards, the results backend still uses the former one.

## Checklist

* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What did you do?

In my remoulade conf file:

```python
RESULT_BACKEND = RedisBackend(client=REDIS_INSTANCE)
BROKER = RabbitmqBroker(host='localhost')
BROKER.add_middleware(Results(backend=RESULT_BACKEND, store_results=True))
dramatiq.set_broker(BROKER)
dramatiq.set_encoder(dramatiq.PickleEncoder())
```

## What did you expect would happen?

I expected `RedisBackend` to use `PickleEncoder` as `BROKER` does.

## What happened?

`RedisBackend` uses `JSONEncoder`

## Workaround

```python
# Set encoder before backend otherwise it is not used
dramatiq.set_encoder(dramatiq.PickleEncoder())

RESULT_BACKEND = RedisBackend(client=REDIS_INSTANCE)
BROKER = RabbitmqBroker(host='localhost')
BROKER.add_middleware(Results(backend=RESULT_BACKEND, store_results=True))
dramatiq.set_broker(BROKER)
```

**Comment by mehdigmira** [comment]
I think there should only be one encoder for the whole remoulade project.
We should have some smart JSON encoder that handles dates, etc. and drop support for other encoders.

**Comment by etiennecrb** [comment]
See https://github.com/Bogdanp/dramatiq/pull/108/files

**Comment by SimonDosda** [comment]
solved
