### ISSUE TITLE
Add a state attribute in result

### ISSUE THREAD

**Issue by etiennecrb** [wiremind/remoulade#98]
It could be interesting to provide a state attribute in the Result class as [celery task states](https://docs.celeryproject.org/en/latest/reference/celery.states.html#misc). Possible values:

- PENDING
- SUCCESS
- FAILURE
- REVOKED

**Comment by antoinerabany** [comment]
SUCCESS and FAILURE can be accessed via ResultBackend, REVOKED via canceled backend. The only one which is missing is PENDING, do you think there should be another backend to store this ?

**Comment by antoinerabany** [comment]
will be implemented in #106
